AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  item-tracking

  Sample SAM Template for item-tracking
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ItemTrackingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - arm64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemTrackingDB
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TB_ITEM_TRACKING: !Ref ItemTrackingDB
          NTBA_FIX_319: 1
  ItemTrackingDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: pk
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ItemTrackingFunction:
    Description: "ItemTrackingFunction ARN"
    Value: !GetAtt ItemTrackingFunction.Arn
  ItemTrackingFunctionIamRole:
    Description: "Implicit IAM Role created for ItemTrackingFunction"
    Value: !GetAtt ItemTrackingFunction.Arn
